[package]
name = "ggfb"
version = "0.2.0"
edition = "2018"
description = "Crust - another git cli tool"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
structopt = "0.3.26"
